pipeline { 
  agent any
  
  tools {
    maven 'maven 3.6.1'
  }
  stages {
    stage ("build") {
      when {
        changeset "**/worker/**"
      }
      steps {
      echo 'Compiling worker app'
      dir('worker') {
        sh 'mvn compile'
        }  
      }
    }
    stage ("test") {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Running Unit Tests on worker app'
        dir ('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage ("Package") {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging Worker app'
        dir ('worker') {
          sh'mvn package -DskipTests'
        }
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      echo 'Building multibrance pipeline for worker is completed..'
    }
  }
}
